### ISSUE TITLE
Error in "AntdBaseMixin"

### ISSUE THREAD

**Issue by jifer-dev** [seewindcn/reflex-antd#2]
`    self._init_contains(contains, exs)
  File "/Users/jifer/Documents/projects/kaspi_system/.venv/lib/python3.11/site-packages/reflex_antd/base.py", line 656, in _init_contains
    self._custom_components |= v.get_custom_components()
TypeError: unsupported operand type(s) for |=: 'ModelPrivateAttr' and 'set'`

**Comment by jifer-dev** [comment]
As I understand it, the problem is related to the use of `PrivateAttr` from pydantic v2, and to fix the error you need to use `PrivateAttr` from pydantic v1

**Comment by seewindcn** [comment]
can you provide more information? for example, your code which use ModelPrivateAttr?

**Comment by jifer-dev** [comment]
I found the cause of this problem. This is due to the fact that after the last reflex update, I installed pydantic v2 and the import `from pydantic import PrivateAttr` leads to this error due to the fact that `PrivateAttr` is imported from pydantic v2

**Comment by seewindcn** [comment]
got it, update to fix it
