### ISSUE TITLE
The tree component is not working

### ISSUE THREAD

**Issue by RustyKobie** [seewindcn/reflex-antd#3]
"/opt/homebrew/Caskroom/miniforge/base/envs/reflex_frontend/lib/python3.10/site-packages/reflex/components/component.py", 
line 325, in __init__
    raise TypeError(
TypeError: Invalid var passed for prop theme, expected type typing.Union[reflex_antd.base.ContainVar, typing.Dict], got 
value theme.styles.global.body.antd of type <class 'str'>.

**Comment by seewindcn** [comment]
thanks, it is a bug about theme's code, fix;

**Comment by RustyKobie** [comment]
Thanks @seewindcn, will you be able to update the pip package as well?
